# Generated by Django 4.2.3 on 2023-07-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeding',
        ),
    ]
