# Generated by Django 4.2.3 on 2023-07-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_toy_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
